spring.application.name=todo

# Configuración de la Base de Datos H2 (en memoria)
spring.datasource.url=jdbc:h2:mem:todolistdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración de la Consola H2 para visualizar los datos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Desactivar la protección de frames para poder abrir la consola H2 en el navegador
spring.h2.console.settings.web-allow-others=true

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
